repos:
- repo: .pre-commit-hooks/
  rev: master
  hooks:
   -   id: ormolu
       exclude: Hercules/Agent/Compat.hs$
   -   id: shellcheck
   #-   id: hlint
   -   id: nixpkgs-fmt
       exclude: (tests/agent-test/testdata)

